"""Initial migration

Revision ID: 5bc1457bb27f
Revises: 
Create Date: 2025-01-08 23:11:47.335748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bc1457bb27f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('income_statement',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('revenue', sa.BigInteger(), nullable=True),
    sa.Column('grossProfit', sa.BigInteger(), nullable=True),
    sa.Column('operatingIncome', sa.BigInteger(), nullable=True),
    sa.Column('netIncome', sa.BigInteger(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('income_statement')
    # ### end Alembic commands ###
